@api=http://localhost:3000/descuento

POST {{api}}
Content-Type: application/json

{
  "nombre": "Oferta de invierno",
  "tipo_descuento": "%",
  "valor":45 
}
###
GET {{api}}/1
###
PUT {{api}}/5
Content-Type: application/json

{
  "nombre": "Oferta de invierno",
  "tipo_descuento": "$",
  "valor":100
}
###
GEt {{api}}

###
DELETE {{api}}/1