
@api=http://localhost:3000

POST {{api}}/registro
Content-Type: application/json

{
  "nombre": "Pepe Lopez",
  "email": "lola@gmail.com",
  "password": "1223445678",
  "pais": "Perú"
}
###
POST {{api}}/login
Content-Type: application/json

{
  "email": "pep07@gmail.com",
  "password": "holamundo"
}